# Generated by Django 5.2.3 on 2025-11-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
